---
title: "Neural Networks Models"
header-includes:
   - \usepackage{float}
output: 
  html_document: 
    theme: readable
    fig_caption: yes
    number_sections: yes
    toc: yes
    code_folding: show
    df_print: paged
editor_options: 
  chunk_output_type: console
---

# **Exercise:** 

> 1. For Boston housing data, please fit a neural network model with `neuralnet` package using 2 hidden layer, `hidden=c(3,2)` and provide both in-sample and out-of-sample average sum squares. 

```{r echo=FALSE, eval=FALSE}
library(MASS)
maxs <- apply(Boston, 2, max) 
mins <- apply(Boston, 2, min)

scaled <- as.data.frame(scale(Boston, center = mins, scale = maxs - mins))
index <- sample(1:nrow(Boston),round(0.9*nrow(Boston)))

train_Boston <- scaled[index,]
test_Boston <- scaled[-index,]

library(neuralnet)
n <- names(train_Boston)
f <- as.formula(paste("medv ~", paste(n[!n %in% "medv"], collapse = " + ")))
nn <- neuralnet(f,data=train_Boston, hidden=c(3,2), linear.output=T)
plot(nn)
```

> 2. For Bankruptcy dataset, what are the in-sample and out-of-sample AUC using only one layer with 5 neurons? 

```{r echo=FALSE, eval=FALSE}
Bank_data <- read.csv(file = "https://xiaoruizhu.github.io/Data-Mining-R/lecture/data/bankruptcy.csv", header=T)
# summary(Bank_data)
library(MASS)
# maxs <- apply(Bank_data[,-c(1:3)], 2, max) 
# mins <- apply(Bank_data[,-c(1:3)], 2, min)
Bank_data_scaled <- Bank_data
# Bank_data_scaled[,-c(1:3)] <- as.data.frame(scale(Bank_data[,-c(1:3)], center = mins, scale = maxs - mins))

sample_index <- sample(nrow(Bank_data_scaled),nrow(Bank_data_scaled)*0.70)
Bank_train <- Bank_data_scaled[sample_index,]
Bank_test <- Bank_data_scaled[-sample_index,]

library(neuralnet)
n <- names(Bank_train)
f <- as.formula(paste("DLRSN ~", paste(n[-c(1:3)], collapse = " + ")))
Bank_nn <- neuralnet(f, data=Bank_train, hidden=c(5), algorithm = 'rprop+', linear.output=T, likelihood = T)
# plot(Bank_nn)

library(ROCR)
pcut_nn <- 1/36
prob_nn_in <-predict(Bank_nn, Bank_train, type="response")
pred_nn_in <- (prob_nn_in>=pcut_nn)*1
table(Bank_train$DLRSN, pred_nn_in, dnn=c("Observed","Predicted"))

pred <- prediction(prob_nn_in, Bank_train$DLRSN)
perf <- performance(pred, "tpr", "fpr")
plot(perf, colorize=TRUE)
#Get the AUC
unlist(slot(performance(pred, "auc"), "y.values"))

# Out-of-sample AUC
prob_nn_out <- predict(Bank_nn, Bank_test, type="response")
pred_nn_out <- (prob_nn_out>=pcut_nn)*1
table(Bank_test$DLRSN, pred_nn_out, dnn=c("Observed","Predicted"))

pred <- prediction(prob_nn_out, Bank_test$DLRSN)
perf <- performance(pred, "tpr", "fpr")
plot(perf, colorize=TRUE)
#Get the AUC
unlist(slot(performance(pred, "auc"), "y.values"))
```