---
title: "Monte Carlo Simulation"
output: 
  html_document: 
    theme: readable
    fig_caption: yes
    number_sections: yes
    toc: yes
  html_notebook: 
    fig_caption: yes
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

# Simulation Exercise

Assume mean function $E(y|x)= 5 + 1.2*x_1 +3*x_2$

- Generate data with $x_1 \sim N(2,.4^2)$, $x_2 \sim N(-1, .1^2)$, sample size $n=200$, and error term $\varepsilon\sim N(0,\sigma^2)$, where $\sigma^2=1$.

```{r , eval=FALSE}
#sample code for hw2 p3
#monte carlo simulation
n <- 200 #sample size
m <- 100 #number of simulation iterations
#part i) simulate predictors X

#part ii)
for(j in 1:m){
  #simulate the error term m=100 times...
  #generate response vector y with error term per iteration
  lm.out <- ?? #fit linear regression
  betaMatrix[j,] <- lm.out$coefficients
  mysummary <- summary(lm.out)
  listMSE[j] <- mysummary$sigma^2 #get MSE per iteration
  }
#part iii) compute MSE bias etc
beta_mean <- apply(betaMatrix,2,mean)
beta_var <- apply(betaMatrix,2,var)
```

```{r , echo=FALSE, eval=FALSE}
# x1~N(2, .4^2), x2 ~ N(-1, .1^2), sample size n=200
m <- 1000 # simulation times
coef <- c(5, 1.2, 3)

nseq <- seq(from=200, to=2000, by=200)
resultA <- matrix(NA, nrow = 1, ncol = 10)

for (j in nseq) {
  x1 <- rnorm(n = j, mean = 2, sd = .4)
  x2 <- rnorm(n = j, mean = -1, sd = .1)
  fitcoef <- matrix(NA, m, 3)
  for (i in 1:m) {
    er <- rnorm(n = j, mean = 0, sd = 1)
    simD <- data.frame(y=coef[1] + cbind(x1, x2) %*% coef[-1] + er, x1, x2)
    mod <- lm(formula = y~x1+x2, data = simD)
    fitcoef[i,] <- coef(mod)
    }
  # head(fitcoef)
  biasBetas <- (colSums(fitcoef))/m - coef
  VarBetas <- colSums(sweep(fitcoef, 2, coef)^2)/m
  # biasBetas; VarBetas
  mseBetas <- biasBetas^2 + VarBetas
  # mseBetas
  temp <- cbind(Size=j, Bias1=biasBetas[1], Var1=VarBetas[1], MSE1=mseBetas[1],
                   Bias2=biasBetas[2], Var2=VarBetas[2], MSE2=mseBetas[2],
                   Bias3=biasBetas[3], Var3=VarBetas[3], MSE3=mseBetas[3])
  resultA <- rbind(resultA, temp)
}

resultA <- resultA[-1, ]
```


[go to top](#header)
