---
title: "Advanced Tree Models -- Boosting Trees"
output: 
  html_document: 
    theme: readable
    fig_caption: yes
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Exercise:** 

## Regression problem: Boston housign data

Apply Boosting Trees on the Boston housing data

> 1. Draw the MSE of Boosting Trees with different numbers of trees; 
> 2. Calculate the out of bag prediction error.

```{r, eval=FALSE, echo=FALSE}
### Load the data
data(Boston)
index <- sample(nrow(Boston),nrow(Boston)*0.60)
boston.train <- Boston[index,]
boston.test <- Boston[-index,]

### Boosting for regression trees
boston.boost<- gbm(medv~., data = boston.train, distribution = "gaussian", n.trees = 10000, shrinkage = 0.01, interaction.depth = 8)
summary(boston.boost)

par(mfrow=c(1,2))
plot(boston.boost, i="lstat")
plot(boston.boost, i="rm")

#MSPE
boston.boost.pred.test<- predict(boston.boost, boston.test, n.trees = 10000)
mean((boston.test$medv-boston.boost.pred.test)^2)

# different numbers of tree
ntree<- seq(100, 10000, 100)
predmat<- predict(boston.boost, newdata = boston.test, n.trees = ntree)
err<- apply((predmat-boston.test$medv)^2, 2, mean)
plot(ntree, err, type = 'l', col=2, lwd=2, xlab = "n.trees", ylab = "Test MSE")
abline(h=min(test.err), lty=2)
```

## Classification problem: Credit default data

Apply Boosting Trees on the Credit default data

> 1. Draw the ROC, calculate the AUC.

```{r, eval=FALSE, echo=FALSE}
# load credit card data
credit.data <- read.csv("https://xiaoruizhu.github.io/Data-Mining-R/lecture/data/credit_default.csv", header=T)
# convert categorical variables
credit.data$SEX<- as.factor(credit.data$SEX)
credit.data$EDUCATION<- as.factor(credit.data$EDUCATION)
credit.data$MARRIAGE<- as.factor(credit.data$MARRIAGE)
# random splitting
index <- sample(nrow(credit.data),nrow(credit.data)*0.60)
credit.train = credit.data[index,]
credit.test = credit.data[-index,]

### Boosting for classification trees
credit.train$default.payment.next.month= as.factor(credit.train$default.payment.next.month)
credit.boost= boosting(default.payment.next.month~., data = credit.train, boos = T)
save(credit.boost, file = "credit.boost.Rdata")

# Training AUC
pred.credit.boost= predict(credit.boost, newdata = credit.train)
pred <- ROCR::prediction(pred.credit.boost$prob[,2], credit.train$default.payment.next.month)
perf <- performance(pred, "tpr", "fpr")
plot(perf, colorize=TRUE)
#Get the AUC
unlist(slot(performance(pred, "auc"), "y.values"))

pred.credit.boost= predict(credit.boost, newdata = credit.test)
# Testing AUC
pred <- ROCR::prediction(pred.credit.boost$prob[,2], credit.test$default.payment.next.month)
perf <- performance(pred, "tpr", "fpr")
plot(perf, colorize=TRUE)
#Get the AUC
unlist(slot(performance(pred, "auc"), "y.values"))

```
