title: "Data Mining in R"
description: "By Xiaorui Zhu, Brittany Green, and Yan Yu <br /> The greatest truths are the simplest. -- Tao Te Ching <br /> Thinking details thoughtfully, solving in whole elegantly. -- Xiaorui Zhu"
show_downloads: FALSE
theme: jekyll-theme-cayman
google_analytics: [UA-54280540-4]
markdown: kramdown
